/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/closers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Closers */
        get: operations["get_closers_api_closers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Compare */
        get: operations["get_compare_api_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/databank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Databank */
        get: operations["get_databank_api_databank_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/draft/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Draft Recommend */
        post: operations["draft_recommend_api_draft_recommend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/draft/simulate-picks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Draft Simulate Picks */
        post: operations["draft_simulate_picks_api_draft_simulate_picks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/free-agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Free Agents */
        get: operations["get_free_agents_api_free_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leaders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Leaders */
        get: operations["get_leaders_api_leaders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lineup/optimize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Optimize Lineup */
        post: operations["optimize_lineup_api_lineup_optimize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lineup/set": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Lineup */
        post: operations["set_lineup_api_lineup_set_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matchup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Matchup */
        get: operations["get_matchup_api_matchup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Team */
        get: operations["get_my_team_api_me_team_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/punt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Punt */
        get: operations["get_punt_api_punt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/standings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Standings */
        get: operations["get_standings_api_standings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streaming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Streaming */
        get: operations["get_streaming_api_streaming_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trade-finder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trade Finder */
        get: operations["get_trade_finder_api_trade_finder_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trade/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate Trade Endpoint */
        post: operations["evaluate_trade_endpoint_api_trade_evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/add-drop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Drop */
        post: operations["add_drop_api_transactions_add_drop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddDropRequest */
        AddDropRequest: {
            /** Add Player Key */
            add_player_key?: string | null;
            /** Drop Player Key */
            drop_player_key?: string | null;
        };
        /** CategoryImpact */
        CategoryImpact: {
            /** Cat */
            cat: string;
            /** Delta */
            delta: number;
        };
        /** CategoryLine */
        CategoryLine: {
            /** Cat */
            cat: string;
            /** Edge */
            edge: number;
            /**
             * Inverse
             * @default false
             */
            inverse: boolean;
            /** Opp */
            opp: number;
            /** Win Prob */
            win_prob: number;
            /** You */
            you: number;
        };
        /** CloserEntry */
        CloserEntry: {
            closer?: components["schemas"]["PlayerRef"] | null;
            /**
             * Confidence
             * @default
             */
            confidence: string;
            /**
             * Handcuffs
             * @default []
             */
            handcuffs: components["schemas"]["PlayerRef"][];
            /**
             * Role
             * @default
             */
            role: string;
            /** Team */
            team: string;
        };
        /** ClosersResponse */
        ClosersResponse: {
            /** Entries */
            entries: components["schemas"]["CloserEntry"][];
        };
        /** ComparePlayer */
        ComparePlayer: {
            player: components["schemas"]["PlayerRef"];
            /**
             * Stats
             * @default {}
             */
            stats: {
                [key: string]: number;
            };
        };
        /** CompareResponse */
        CompareResponse: {
            /**
             * Categories
             * @default []
             */
            categories: string[];
            /**
             * Players
             * @default []
             */
            players: components["schemas"]["ComparePlayer"][];
        };
        /** DatabankResponse */
        DatabankResponse: {
            player: components["schemas"]["PlayerRef"];
            /**
             * Seasons
             * @default []
             */
            seasons: components["schemas"]["SeasonStat"][];
        };
        /** DraftClock */
        DraftClock: {
            /** Current Pick */
            current_pick: number;
            /** Is User Turn */
            is_user_turn: boolean;
            /** Pick In Round */
            pick_in_round: number;
            /** Picking Team Index */
            picking_team_index: number;
            /** Round */
            round: number;
        };
        /** DraftConfig */
        DraftConfig: {
            /**
             * Num Rounds
             * @default 23
             */
            num_rounds: number;
            /**
             * Num Teams
             * @default 12
             */
            num_teams: number;
            /** Roster Config */
            roster_config?: {
                [key: string]: number;
            } | null;
            /**
             * User Team Index
             * @default 0
             */
            user_team_index: number;
        };
        /** DraftPick */
        DraftPick: {
            /** Pick */
            pick: number;
            /** Player Id */
            player_id: number;
            /** Player Name */
            player_name: string;
            /** Positions */
            positions: string;
            /** Team Index */
            team_index: number;
        };
        /** DraftRecommendRequest */
        DraftRecommendRequest: {
            /**
             * @default {
             *       "num_rounds": 23,
             *       "num_teams": 12,
             *       "user_team_index": 0
             *     }
             */
            config: components["schemas"]["DraftConfig"];
            /**
             * N Simulations
             * @default 300
             */
            n_simulations: number;
            /**
             * Pick Log
             * @default []
             */
            pick_log: components["schemas"]["DraftPick"][];
            /**
             * Top N
             * @default 8
             */
            top_n: number;
        };
        /** DraftRecommendResponse */
        DraftRecommendResponse: {
            clock: components["schemas"]["DraftClock"];
            /** Recommendations */
            recommendations: components["schemas"]["DraftRecommendation"][];
            /**
             * Summary
             * @default
             */
            summary: string;
        };
        /** DraftRecommendation */
        DraftRecommendation: {
            /** Confidence */
            confidence?: string | null;
            player: components["schemas"]["PlayerRef"];
            /** Projected Sgp */
            projected_sgp: number;
            /** Rank */
            rank: number;
            /**
             * Reason
             * @default
             */
            reason: string;
            /** Score */
            score: number;
            /** Tag */
            tag?: string | null;
        };
        /** DraftSimulatePicksRequest */
        DraftSimulatePicksRequest: {
            /**
             * @default {
             *       "num_rounds": 23,
             *       "num_teams": 12,
             *       "user_team_index": 0
             *     }
             */
            config: components["schemas"]["DraftConfig"];
            /**
             * Pick Log
             * @default []
             */
            pick_log: components["schemas"]["DraftPick"][];
            /** Seed */
            seed?: number | null;
        };
        /** DraftSimulatePicksResponse */
        DraftSimulatePicksResponse: {
            clock: components["schemas"]["DraftClock"];
            /**
             * Picks
             * @default []
             */
            picks: components["schemas"]["DraftPick"][];
            /**
             * Summary
             * @default
             */
            summary: string;
        };
        /** FreeAgentRec */
        FreeAgentRec: {
            add: components["schemas"]["PlayerRef"];
            /**
             * Categories Helped
             * @default []
             */
            categories_helped: string[];
            drop?: components["schemas"]["PlayerRef"] | null;
            /** Marginal Value */
            marginal_value: number;
            /** Ownership Pct */
            ownership_pct?: number | null;
            /**
             * Rationale
             * @default
             */
            rationale: string;
        };
        /** FreeAgentsResponse */
        FreeAgentsResponse: {
            /** Recommendations */
            recommendations: components["schemas"]["FreeAgentRec"][];
            /** Team Name */
            team_name: string;
        };
        /** GradeRange */
        GradeRange: {
            /** Center */
            center: number;
            /** Grade */
            grade: string;
            /** High */
            high: number;
            /** Low */
            low: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LeaderRow */
        LeaderRow: {
            player: components["schemas"]["PlayerRef"];
            /** Rank */
            rank: number;
            /** Value */
            value: number;
        };
        /** LeadersResponse */
        LeadersResponse: {
            /** Category */
            category: string;
            /** Rows */
            rows: components["schemas"]["LeaderRow"][];
        };
        /** LineupAssignment */
        LineupAssignment: {
            /** Player Id */
            player_id?: number | null;
            /** Slot */
            slot: string;
            /** Yahoo Player Key */
            yahoo_player_key: string;
        };
        /** LineupOptimizeRequest */
        LineupOptimizeRequest: {
            /** Date */
            date?: string | null;
            /**
             * Scope
             * @default rest_of_season
             */
            scope: string;
            /** Team Name */
            team_name: string;
        };
        /** LineupOptimizeResponse */
        LineupOptimizeResponse: {
            /** Date */
            date: string;
            /** Slots */
            slots: components["schemas"]["LineupSlot"][];
            /**
             * Summary
             * @default
             */
            summary: string;
            /** Team Name */
            team_name: string;
        };
        /** LineupSetRequest */
        LineupSetRequest: {
            /** Assignments */
            assignments: components["schemas"]["LineupAssignment"][];
            /** Date */
            date: string;
            /** Team Name */
            team_name: string;
        };
        /** LineupSlot */
        LineupSlot: {
            /** Action */
            action: string;
            /**
             * Forced Start
             * @default false
             */
            forced_start: boolean;
            player: components["schemas"]["PlayerRef"];
            /** Projected */
            projected: number;
            /** Reason */
            reason?: string | null;
            /** Slot */
            slot: string;
        };
        /** MatchupCategory */
        MatchupCategory: {
            /** Cat */
            cat: string;
            /**
             * Inverse
             * @default false
             */
            inverse: boolean;
            /** Opp */
            opp: number;
            /** Win Prob */
            win_prob: number;
            /** You */
            you: number;
        };
        /** MatchupHero */
        MatchupHero: {
            /** Loss Prob */
            loss_prob: number;
            /** Opponent */
            opponent: string;
            /** Tie Prob */
            tie_prob: number;
            /** Week */
            week: number;
            /** Win Prob */
            win_prob: number;
        };
        /** MatchupResponse */
        MatchupResponse: {
            /**
             * Categories
             * @default []
             */
            categories: components["schemas"]["MatchupCategory"][];
            /**
             * Opponent
             * @default
             */
            opponent: string;
            /**
             * Projected Cat Wins
             * @default 0
             */
            projected_cat_wins: number;
            /** Team Name */
            team_name: string;
            /**
             * Week
             * @default 0
             */
            week: number;
            /**
             * Win Prob
             * @default 0
             */
            win_prob: number;
        };
        /** MutationResult */
        MutationResult: {
            /** Applied */
            applied?: number | null;
            /** Error */
            error?: string | null;
            /** Ok */
            ok: boolean;
            /** Status */
            status?: number | null;
        };
        /** MyTeamResponse */
        MyTeamResponse: {
            /** Categories */
            categories: components["schemas"]["CategoryLine"][];
            matchup: components["schemas"]["MatchupHero"] | null;
            /** Rank */
            rank: number;
            /** Record */
            record: string;
            /** Team Name */
            team_name: string;
        };
        /** PlayerRef */
        PlayerRef: {
            /** Id */
            id: number;
            /** Mlb Id */
            mlb_id?: number | null;
            /** Name */
            name: string;
            /** Positions */
            positions: string;
            /** Team Abbr */
            team_abbr?: string | null;
            /** Team Id */
            team_id?: number | null;
            /** Yahoo Player Key */
            yahoo_player_key?: string | null;
        };
        /** PuntCategory */
        PuntCategory: {
            /** Cat */
            cat: string;
            /** Current Rank */
            current_rank: number;
            /** Gainable */
            gainable: boolean;
            /**
             * Recommendation
             * @default
             */
            recommendation: string;
        };
        /** PuntResponse */
        PuntResponse: {
            /**
             * Categories
             * @default []
             */
            categories: components["schemas"]["PuntCategory"][];
            /**
             * Punt Candidates
             * @default []
             */
            punt_candidates: string[];
            /** Team Name */
            team_name: string;
        };
        /** SeasonStat */
        SeasonStat: {
            /**
             * Stats
             * @default {}
             */
            stats: {
                [key: string]: number;
            };
            /** Year */
            year: number;
        };
        /** StandingsResponse */
        StandingsResponse: {
            /** Teams */
            teams: components["schemas"]["TeamStanding"][];
        };
        /** StreamCandidate */
        StreamCandidate: {
            /**
             * Actionable
             * @default true
             */
            actionable: boolean;
            /**
             * Opponent
             * @default
             */
            opponent: string;
            player: components["schemas"]["PlayerRef"];
            /**
             * Reason
             * @default
             */
            reason: string;
            /**
             * Score
             * @default 0
             */
            score: number;
            /**
             * Status
             * @default
             */
            status: string;
            /**
             * Team
             * @default
             */
            team: string;
        };
        /** StreamingResponse */
        StreamingResponse: {
            /** Candidates */
            candidates: components["schemas"]["StreamCandidate"][];
            /** Date */
            date: string;
        };
        /** TeamStanding */
        TeamStanding: {
            /**
             * Category Ranks
             * @default {}
             */
            category_ranks: {
                [key: string]: number;
            };
            /**
             * Losses
             * @default 0
             */
            losses: number;
            /**
             * Points
             * @default 0
             */
            points: number;
            /** Rank */
            rank: number;
            /** Team Name */
            team_name: string;
            /**
             * Ties
             * @default 0
             */
            ties: number;
            /**
             * Wins
             * @default 0
             */
            wins: number;
        };
        /** TradeEvaluateRequest */
        TradeEvaluateRequest: {
            /**
             * Enable Mc
             * @default false
             */
            enable_mc: boolean;
            /** Giving Ids */
            giving_ids: number[];
            /** Receiving Ids */
            receiving_ids: number[];
            /** Team Name */
            team_name: string;
        };
        /** TradeEvaluationResponse */
        TradeEvaluationResponse: {
            /**
             * Category Impacts
             * @default []
             */
            category_impacts: components["schemas"]["CategoryImpact"][];
            /**
             * Confidence Pct
             * @default 0
             */
            confidence_pct: number;
            /** Delta Champ Prob */
            delta_champ_prob?: number | null;
            /** Delta Playoff Prob */
            delta_playoff_prob?: number | null;
            /**
             * Giving
             * @default []
             */
            giving: components["schemas"]["PlayerRef"][];
            /**
             * Grade
             * @default
             */
            grade: string;
            grade_range?: components["schemas"]["GradeRange"] | null;
            /**
             * Mc Enabled
             * @default false
             */
            mc_enabled: boolean;
            /**
             * Receiving
             * @default []
             */
            receiving: components["schemas"]["PlayerRef"][];
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Surplus Sgp
             * @default 0
             */
            surplus_sgp: number;
            /**
             * Verdict
             * @default
             */
            verdict: string;
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
        };
        /** TradeFinderResponse */
        TradeFinderResponse: {
            /**
             * Suggestions
             * @default []
             */
            suggestions: components["schemas"]["TradeSuggestion"][];
            /** Team Name */
            team_name: string;
        };
        /** TradeSuggestion */
        TradeSuggestion: {
            /**
             * Giving
             * @default []
             */
            giving: components["schemas"]["PlayerRef"][];
            /**
             * Net Sgp
             * @default 0
             */
            net_sgp: number;
            /** Partner Team */
            partner_team: string;
            /**
             * Rationale
             * @default
             */
            rationale: string;
            /**
             * Receiving
             * @default []
             */
            receiving: components["schemas"]["PlayerRef"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_closers_api_closers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClosersResponse"];
                };
            };
        };
    };
    get_compare_api_compare_get: {
        parameters: {
            query?: {
                ids?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_databank_api_databank_get: {
        parameters: {
            query?: {
                player_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatabankResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    draft_recommend_api_draft_recommend_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftRecommendRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftRecommendResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    draft_simulate_picks_api_draft_simulate_picks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftSimulatePicksRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftSimulatePicksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_free_agents_api_free_agents_get: {
        parameters: {
            query: {
                team_name: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FreeAgentsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_leaders_api_leaders_get: {
        parameters: {
            query?: {
                category?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optimize_lineup_api_lineup_optimize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LineupOptimizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineupOptimizeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_lineup_api_lineup_set_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LineupSetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationResult"];
                };
            };
            /** @description Authentication required: missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_matchup_api_matchup_get: {
        parameters: {
            query?: {
                team_name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_team_api_me_team_get: {
        parameters: {
            query: {
                team_name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyTeamResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_punt_api_punt_get: {
        parameters: {
            query?: {
                team_name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PuntResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_standings_api_standings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandingsResponse"];
                };
            };
        };
    };
    get_streaming_api_streaming_get: {
        parameters: {
            query?: {
                date?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trade_finder_api_trade_finder_get: {
        parameters: {
            query?: {
                team_name?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeFinderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_trade_endpoint_api_trade_evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TradeEvaluateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeEvaluationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_drop_api_transactions_add_drop_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddDropRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationResult"];
                };
            };
            /** @description Authentication required: missing or invalid bearer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
