"""Centralized registry of all hardcoded constants in the Lineup Optimizer.

Every magic number used in the optimizer pipeline is registered here with:
- A citation to published research or empirical calibration source
- Plausible bounds for sensitivity analysis / perturbation testing
- A sensitivity classification (HIGH, MEDIUM, LOW)

This replaces scattered inline comments and enables systematic validation.
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class ConstantEntry:
    """A registered optimizer constant."""

    value: float
    lower_bound: float
    upper_bound: float
    citation: str
    module: str
    sensitivity: str
    description: str


CONSTANTS_REGISTRY: dict[str, ConstantEntry] = {
    # -- Platoon Adjustments (The Book baseline, updated 2020-2024) --------
    "platoon_lhb_vs_rhp": ConstantEntry(
        value=0.075,
        lower_bound=0.05,
        upper_bound=0.12,
        citation="The Book (Tango et al. 2007) baseline; updated with 2020-2024 FanGraphs split data",
        module="matchup_adjustments.py",
        sensitivity="MEDIUM",
        description="wOBA advantage for LHB vs RHP (7.5%, was 8.6% in The Book 2007)",
    ),
    "platoon_rhb_vs_lhp": ConstantEntry(
        value=0.058,
        lower_bound=0.03,
        upper_bound=0.10,
        citation="The Book (Tango et al. 2007) baseline; updated with 2020-2024 FanGraphs split data",
        module="matchup_adjustments.py",
        sensitivity="MEDIUM",
        description="wOBA advantage for RHB vs LHP (5.8%, was 6.1% in The Book 2007)",
    ),
    "platoon_stab_lhb": ConstantEntry(
        value=1000,
        lower_bound=500,
        upper_bound=1500,
        citation="Pizza Cutter (Russell Carleton) stabilization research; FanGraphs",
        module="matchup_adjustments.py",
        sensitivity="LOW",
        description="PA for LHB platoon split to stabilize",
    ),
    "platoon_stab_rhb": ConstantEntry(
        value=2200,
        lower_bound=1500,
        upper_bound=3000,
        citation="Pizza Cutter (Russell Carleton) stabilization research; FanGraphs",
        module="matchup_adjustments.py",
        sensitivity="LOW",
        description="PA for RHB platoon split to stabilize",
    ),
    # -- Start/Sit ---------------------------------------------------------
    "home_advantage": ConstantEntry(
        value=1.02,
        lower_bound=1.01,
        upper_bound=1.04,
        citation="Historical MLB data: ~54% home win rate (Retrosheet 2000-2024)",
        module="start_sit.py",
        sensitivity="LOW",
        description="Home team counting stat multiplier",
    ),
    "away_discount": ConstantEntry(
        value=0.97,
        lower_bound=0.95,
        upper_bound=0.99,
        citation="Symmetric complement of home_advantage",
        module="start_sit.py",
        sensitivity="LOW",
        description="Away team counting stat multiplier",
    ),
    # -- Bayesian Stabilization Points -------------------------------------
    "stabilization_hr_rate": ConstantEntry(
        value=170,
        lower_bound=130,
        upper_bound=210,
        citation="FanGraphs: 'How Long Until a Hitter's Stats Stabilize?' (2014); Russell Carleton",
        module="projections.py",
        sensitivity="HIGH",
        description="PA for HR rate to stabilize (Bayesian prior weight)",
    ),
    "stabilization_avg": ConstantEntry(
        value=910,
        lower_bound=700,
        upper_bound=1100,
        citation="FanGraphs stabilization series; BABIP dependency requires large sample",
        module="projections.py",
        sensitivity="HIGH",
        description="PA for batting average to stabilize",
    ),
    "stabilization_obp": ConstantEntry(
        value=460,
        lower_bound=350,
        upper_bound=600,
        citation="FanGraphs stabilization series; BB rate stabilizes faster than AVG",
        module="projections.py",
        sensitivity="HIGH",
        description="PA for OBP to stabilize",
    ),
    "stabilization_era": ConstantEntry(
        value=630,
        lower_bound=450,
        upper_bound=800,
        citation="FanGraphs: measured in batters faced; ERA has high variance",
        module="projections.py",
        sensitivity="HIGH",
        description="BF for ERA to stabilize",
    ),
    "stabilization_whip": ConstantEntry(
        value=540,
        lower_bound=400,
        upper_bound=700,
        citation="FanGraphs stabilization series; similar to ERA",
        module="projections.py",
        sensitivity="HIGH",
        description="BF for WHIP to stabilize",
    ),
    "stabilization_k_rate": ConstantEntry(
        value=60,
        lower_bound=40,
        upper_bound=80,
        citation="FanGraphs: K rate stabilizes very quickly (~60 PA)",
        module="projections.py",
        sensitivity="MEDIUM",
        description="PA for K rate to stabilize",
    ),
    "stabilization_bb_rate": ConstantEntry(
        value=120,
        lower_bound=80,
        upper_bound=160,
        citation="FanGraphs stabilization series",
        module="projections.py",
        sensitivity="MEDIUM",
        description="PA for BB rate to stabilize",
    ),
    "stabilization_sb_rate": ConstantEntry(
        value=200,
        lower_bound=150,
        upper_bound=300,
        citation="FanGraphs: SB rate requires moderate sample; opportunity-dependent",
        module="projections.py",
        sensitivity="MEDIUM",
        description="PA for SB rate to stabilize",
    ),
    "stabilization_k_rate_pitch": ConstantEntry(
        value=70,
        lower_bound=50,
        upper_bound=100,
        citation="FanGraphs: pitcher K rate stabilizes quickly",
        module="projections.py",
        sensitivity="MEDIUM",
        description="IP for pitcher K rate to stabilize",
    ),
    # -- Recent Form -------------------------------------------------------
    "recent_form_blend": ConstantEntry(
        value=0.25,
        lower_bound=0.10,
        upper_bound=0.35,
        citation="Wave 11B DCV-A1-004: reconciled to 0.25 to match daily_optimizer's dynamic cap and shared_data_layer._RECENT_FORM_WEIGHT_TODAY; was 0.20 (drift)",
        module="projections.py",
        sensitivity="MEDIUM",
        description="Weight of L14 recent form in projection blend (max blend weight reached at 14+ games)",
    ),
    "min_recent_games": ConstantEntry(
        value=7,
        lower_bound=5,
        upper_bound=14,
        citation="Statistical minimum for L14 game log reliability",
        module="projections.py",
        sensitivity="LOW",
        description="Minimum games required to apply recent form adjustment",
    ),
    # -- Scenario Generation -----------------------------------------------
    "default_cv_hr": ConstantEntry(
        value=0.25,
        lower_bound=0.15,
        upper_bound=0.40,
        citation="Empirical: 2022-2024 MLB (N=624 hitters, 400+ PA); cross-sectional CV=0.51, projection ~50%",
        module="scenario_generator.py",
        sensitivity="MEDIUM",
        description="Coefficient of variation for HR projections",
    ),
    "default_cv_sb": ConstantEntry(
        value=0.45,
        lower_bound=0.25,
        upper_bound=0.65,
        citation="Empirical: 2022-2024 MLB (N=624 hitters, 400+ PA); cross-sectional CV=1.10, projection ~0.45",
        module="scenario_generator.py",
        sensitivity="MEDIUM",
        description="Coefficient of variation for SB projections",
    ),
    "default_cv_sv": ConstantEntry(
        value=0.50,
        lower_bound=0.30,
        upper_bound=0.70,
        citation="Empirical: 2022-2024 MLB (N=393 pitchers, 100+ IP); cross-sectional CV=5.78, capped for projection",
        module="scenario_generator.py",
        sensitivity="MEDIUM",
        description="Coefficient of variation for SV projections",
    ),
    "corr_hr_rbi": ConstantEntry(
        value=0.84,
        lower_bound=0.70,
        upper_bound=0.95,
        citation="Empirical: 2022-2024 MLB (N=624 hitters, 400+ PA); HR drives RBI production",
        module="scenario_generator.py",
        sensitivity="LOW",
        description="Correlation between HR and RBI projections",
    ),
    "corr_era_whip": ConstantEntry(
        value=0.81,
        lower_bound=0.65,
        upper_bound=0.92,
        citation="Empirical: 2022-2024 MLB (N=393 pitchers, 100+ IP); ERA and WHIP strongly correlated",
        module="scenario_generator.py",
        sensitivity="LOW",
        description="Correlation between ERA and WHIP projections",
    ),
    # -- Category Urgency --------------------------------------------------
    "sigmoid_k_counting": ConstantEntry(
        value=2.0,
        lower_bound=1.0,
        upper_bound=5.0,
        citation="Calibrated: moderate sensitivity for counting stat gaps; validated via sigmoid_calibrator.py",
        module="category_urgency.py",
        sensitivity="HIGH",
        description="Sigmoid steepness for counting stat urgency",
    ),
    "sigmoid_k_rate": ConstantEntry(
        value=3.0,
        lower_bound=1.5,
        upper_bound=5.0,
        citation="Calibrated: higher sensitivity for noisier rate stat gaps; validated via sigmoid_calibrator.py",
        module="category_urgency.py",
        sensitivity="HIGH",
        description="Sigmoid steepness for rate stat urgency",
    ),
    # -- Streaming ---------------------------------------------------------
    "default_ip_per_start": ConstantEntry(
        value=5.5,
        lower_bound=5.0,
        upper_bound=6.0,
        citation="MLB league average IP/GS (2022-2024): ~5.3-5.6 IP",
        module="streaming.py",
        sensitivity="LOW",
        description="Expected innings per start for average pitcher",
    ),
    "default_team_weekly_ip": ConstantEntry(
        value=54.0,
        lower_bound=45.0,
        upper_bound=65.0,
        citation="Wave 11B DCV-A2-001/A2-003: reconciled to 54.0 to match streaming._STREAM_IP_TARGET + CLAUDE.md gotcha; was 55.0 (drift)",
        module="streaming.py + daily_optimizer.apply_ip_pace_scaling",
        sensitivity="LOW",
        description="Baseline weekly team IP target; canonical value, consumed by streaming.py and apply_ip_pace_scaling",
    ),
    "streaming_baseline_whip": ConstantEntry(
        value=1.30,
        lower_bound=1.10,
        upper_bound=1.40,
        citation="Wave 11B DCV-A2-002: reconciled to 1.30 to match Wave 8d _LEAGUE_AVG_WHIP in streaming.py + war_room_hotcold.py; was 1.25 (drift)",
        module="streaming.py",
        sensitivity="LOW",
        description="Baseline WHIP for streaming pitcher rate-stat impact calculation",
    ),
    "league_avg_era": ConstantEntry(
        value=4.20,
        lower_bound=3.80,
        upper_bound=4.60,
        citation="2026-05-17 Section 3 D1: consolidate 4 different module-level values (4.00 in two_start.py, 4.50 in war_room_hotcold + streaming + in_season + standings_engine). 2025 MLB actual ERA = 4.17.",
        module="war_room_hotcold.py, two_start.py, streaming.py, in_season.py, standings_engine.py",
        sensitivity="MEDIUM",
        description="League-average ERA fallback for pitchers missing live data",
    ),
    "league_avg_whip": ConstantEntry(
        value=1.30,
        lower_bound=1.15,
        upper_bound=1.40,
        citation="2026-05-17 Section 3 D1: consolidate 4 different module-level values (1.25 in two_start.py, 1.30 in war_room_hotcold + streaming + in_season + standings_engine + trade_simulator). 2025 MLB actual WHIP = 1.27.",
        module="war_room_hotcold.py, two_start.py, streaming.py, in_season.py, standings_engine.py, trade_simulator.py",
        sensitivity="MEDIUM",
        description="League-average WHIP fallback for pitchers missing live data",
    ),
    "league_avg_woba": ConstantEntry(
        value=0.320,
        lower_bound=0.305,
        upper_bound=0.335,
        citation="2026-05-17 Section 3 D8: consolidate 2 values (0.315 in engine/context/matchup.py, 0.320 in 5 other modules). 2025 MLB actual wOBA = 0.318.",
        module="streaming.py, matchup_planner.py, in_season.py, waiver_wire.py, engine/context/matchup.py, optimizer/projections.py",
        sensitivity="LOW",
        description="League-average wOBA for opposing-batter quality / fallback baselines",
    ),
    "league_avg_xfip": ConstantEntry(
        value=4.20,
        lower_bound=3.90,
        upper_bound=4.50,
        citation="Wave 11B DCV-A1-009: MLB league-avg xFIP varies yearly (4.05 in 2023, 4.15 in 2024). Annual update procedure: pull from team_strength aggregation or FanGraphs leaderboard.",
        module="daily_optimizer.compute_matchup_multiplier",
        sensitivity="MEDIUM",
        description="League-average xFIP for hitter-vs-pitcher matchup multiplier baseline",
    ),
    "r_stabilization_pa": ConstantEntry(
        value=250.0,
        lower_bound=200.0,
        upper_bound=350.0,
        citation="Wave 11B DCV-A1-007 fix: FanGraphs runs stabilization research; previously 460 (copy-paste of OBP value).",
        module="daily_optimizer.STABILIZATION_POINTS",
        sensitivity="LOW",
        description="PA threshold for runs (R) rate to stabilize in Bayesian blend",
    ),
    "two_start_fatigue_factor": ConstantEntry(
        value=0.93,
        lower_bound=0.85,
        upper_bound=0.98,
        citation="Historical MLB data: 2nd start of week shows ~5-10% ERA/WHIP decay (FanGraphs, short rest studies)",
        module="streaming.py",
        sensitivity="MEDIUM",
        description="Rate stat quality multiplier for 2nd start of the week",
    ),
    "whip_penalty_threshold": ConstantEntry(
        value=1.40,
        lower_bound=1.30,
        upper_bound=1.50,
        citation="Empirical: pitchers above 1.40 WHIP are replacement-level or worse",
        module="streaming.py",
        sensitivity="LOW",
        description="Career WHIP above which streaming composite gets 50% penalty",
    ),
    # -- Pipeline Defaults -------------------------------------------------
    "default_risk_aversion": ConstantEntry(
        value=0.15,
        lower_bound=0.0,
        upper_bound=0.50,
        citation="Empirical: light risk reduction without overfitting to floor",
        module="pipeline.py",
        sensitivity="MEDIUM",
        description="Default lambda for mean-variance risk adjustment",
    ),
    "n_scenarios_standard": ConstantEntry(
        value=200,
        lower_bound=100,
        upper_bound=500,
        citation="Convergence testing: 200 scenarios gives <2% variance in expected value",
        module="pipeline.py",
        sensitivity="LOW",
        description="Number of Monte Carlo scenarios in standard mode",
    ),
    "n_scenarios_full": ConstantEntry(
        value=500,
        lower_bound=200,
        upper_bound=1000,
        citation="Convergence testing: 500 scenarios gives <1% variance; diminishing returns beyond",
        module="pipeline.py",
        sensitivity="LOW",
        description="Number of Monte Carlo scenarios in full mode",
    ),
    # -- Pitcher Quality ---------------------------------------------------
    "pitcher_quality_slope": ConstantEntry(
        value=0.075,
        lower_bound=0.05,
        upper_bound=0.15,
        citation="Calibrated: maps z-score to counting stat multiplier; clamped to +/-15%",
        module="matchup_adjustments.py",
        sensitivity="MEDIUM",
        description="Slope for opposing pitcher quality -> hitter stat multiplier",
    ),
    # -- Replacement Levels (rate-stat marginal SGP) -----------------------
    # Used by daily_optimizer's rate-stat SGP computation:
    # annual_sgp = (component - opportunity * replacement) / raw_denom.
    #
    # OQ-1 resolution (2026-05-15): values are calibrated from FourzynBurn
    # end-of-season standings — they represent the rate-stat performance of
    # the 12th-ranked team (last/replacement tier) per category. Refresh
    # annually after the championship via
    #   `python scripts/calibrate_repl_baselines.py`
    # which reads `league_standings` and writes the new bottom-team values
    # back into this registry.
    "repl_avg": ConstantEntry(
        value=0.240,
        lower_bound=0.225,
        upper_bound=0.255,
        citation="Calibrated from FourzynBurn standings (12th-team AVG); refresh annually via scripts/calibrate_repl_baselines.py (OQ-1)",
        module="daily_optimizer.py",
        sensitivity="HIGH",
        description="Replacement-level AVG for hitter rate-stat marginal SGP",
    ),
    "repl_obp": ConstantEntry(
        value=0.305,
        lower_bound=0.290,
        upper_bound=0.320,
        citation="Calibrated from FourzynBurn standings (12th-team OBP); refresh annually via scripts/calibrate_repl_baselines.py (OQ-1)",
        module="daily_optimizer.py",
        sensitivity="HIGH",
        description="Replacement-level OBP for hitter rate-stat marginal SGP",
    ),
    "repl_era": ConstantEntry(
        value=4.50,
        lower_bound=4.20,
        upper_bound=4.80,
        citation="Calibrated from FourzynBurn standings (12th-team ERA); refresh annually via scripts/calibrate_repl_baselines.py (OQ-1)",
        module="daily_optimizer.py",
        sensitivity="HIGH",
        description="Replacement-level ERA for pitcher rate-stat marginal SGP",
    ),
    "repl_whip": ConstantEntry(
        value=1.35,
        lower_bound=1.27,
        upper_bound=1.42,
        citation="Calibrated from FourzynBurn standings (12th-team WHIP); refresh annually via scripts/calibrate_repl_baselines.py (OQ-1)",
        module="daily_optimizer.py",
        sensitivity="HIGH",
        description="Replacement-level WHIP for pitcher rate-stat marginal SGP",
    ),
    # -- Raw-Unit SGP Denominators (team-volume × per-stand-point denom) --
    # Used alongside replacement levels in rate-stat marginal SGP:
    # annual_sgp = (component - opportunity * replacement) / raw_denom.
    # Derived from team-volume assumptions (5500 AB, 6100 PA, 1400 IP)
    # multiplied by league-config sgp_denominators. See DCV-A1-005 (MED)
    # for the audit finding that these should be derived from actual league
    # data rather than hardcoded.
    "raw_sgp_denom_avg": ConstantEntry(
        value=22.0,
        lower_bound=18.0,
        upper_bound=26.0,
        citation="0.004 AVG/SP × ~5500 team AB; see DCV-A1-005",
        module="daily_optimizer.py",
        sensitivity="MEDIUM",
        description="Raw hits per standings point for AVG (team-volume × per-SP denom)",
    ),
    "raw_sgp_denom_obp": ConstantEntry(
        value=30.0,
        lower_bound=24.0,
        upper_bound=36.0,
        citation="0.005 OBP/SP × ~6100 team PA; see DCV-A1-005",
        module="daily_optimizer.py",
        sensitivity="MEDIUM",
        description="Raw on-base events per standings point for OBP",
    ),
    "raw_sgp_denom_era": ConstantEntry(
        value=31.0,
        lower_bound=25.0,
        upper_bound=37.0,
        citation="0.20 ERA/SP × ~1400 team IP / 9; see DCV-A1-005",
        module="daily_optimizer.py",
        sensitivity="MEDIUM",
        description="Raw earned runs per standings point for ERA",
    ),
    "raw_sgp_denom_whip": ConstantEntry(
        value=28.0,
        lower_bound=23.0,
        upper_bound=33.0,
        citation="0.020 WHIP/SP × ~1400 team IP; see DCV-A1-005",
        module="daily_optimizer.py",
        sensitivity="MEDIUM",
        description="Raw walks+hits per standings point for WHIP",
    ),
    # -- FA Recommender / Waiver Wire (PR9 — 2026-05-21) -------------------
    # The FA engine overhaul (P3) split into ~9 PRs; this PR9 centralizes
    # the previously scattered module-level magic constants from
    # src/optimizer/fa_recommender.py and src/waiver_wire.py into the
    # registry so sensitivity_analysis + sigmoid_calibrator can perturb
    # them and future calibration touches them as first-class inputs.
    "stream_win_prob_min": ConstantEntry(
        value=0.2755,
        lower_bound=0.15,
        upper_bound=0.45,
        citation="Razzball / Pitcher List streaming methodology — categories below ~27.55% week-end win probability are off-board for streaming; PR9 (2026-05-21)",
        module="optimizer/fa_recommender.py",
        sensitivity="HIGH",
        description="Minimum H2H category win probability for a stat to be 'in-play' for streamer surfacing",
    ),
    "floor_pa_min": ConstantEntry(
        value=50,
        lower_bound=20,
        upper_bound=150,
        citation="Internal heuristic 2026-05-20 (FA P3 baseline): PA below ~50 = small-sample noise, apply floor_penalty_mult",
        module="optimizer/fa_recommender.py",
        sensitivity="MEDIUM",
        description="Hitter PA threshold below which a counting-stat floor penalty is applied",
    ),
    "floor_ip_min": ConstantEntry(
        value=20,
        lower_bound=10,
        upper_bound=60,
        citation="Internal heuristic 2026-05-20 (FA P3 baseline): IP below ~20 = small-sample noise, apply floor_penalty_mult",
        module="optimizer/fa_recommender.py",
        sensitivity="MEDIUM",
        description="Pitcher IP threshold below which a counting-stat floor penalty is applied",
    ),
    "ownership_boost_delta": ConstantEntry(
        value=5.0,
        lower_bound=2.0,
        upper_bound=15.0,
        citation="Internal heuristic 2026-05-20 (FA P3 baseline): Yahoo 7-day ownership delta above ~5% indicates trending player worth a boost",
        module="optimizer/fa_recommender.py",
        sensitivity="LOW",
        description="Yahoo ownership 7-day delta threshold (percent points) to trigger ownership boost",
    ),
    "ownership_boost_mult": ConstantEntry(
        value=1.10,
        lower_bound=1.02,
        upper_bound=1.30,
        citation="Internal heuristic 2026-05-20 (FA P3 baseline): conservative 10% boost when ownership delta exceeds threshold",
        module="optimizer/fa_recommender.py",
        sensitivity="LOW",
        description="Multiplier applied to FA score when ownership is trending up significantly",
    ),
    "floor_penalty_mult": ConstantEntry(
        value=0.85,
        lower_bound=0.60,
        upper_bound=0.95,
        citation="Internal heuristic 2026-05-20 (FA P3 baseline): 15% penalty for sub-floor PA/IP small samples",
        module="optimizer/fa_recommender.py",
        sensitivity="MEDIUM",
        description="Multiplicative penalty applied when FA's PA/IP is below floor minimums",
    ),
    "pt_gate_grace_days": ConstantEntry(
        value=30,
        lower_bound=14,
        upper_bound=60,
        citation="FA P3.9 PR21 (2026-05-20): playing-time gate disabled during first 30 days (early-season call-ups + small-sample volatility)",
        module="optimizer/fa_recommender.py",
        sensitivity="MEDIUM",
        description="Days into season before the playing-time gate activates",
    ),
    "pt_ratio_full_credit": ConstantEntry(
        value=0.60,
        lower_bound=0.40,
        upper_bound=0.80,
        citation="FA P3.9 PR21 (2026-05-20): >=60% of expected playing time receives no penalty (1.0x)",
        module="optimizer/fa_recommender.py",
        sensitivity="MEDIUM",
        description="Ratio of actual to expected playing time above which no PT penalty applies",
    ),
    "pt_ratio_mild": ConstantEntry(
        value=0.30,
        lower_bound=0.15,
        upper_bound=0.50,
        citation="FA P3.9 PR21 (2026-05-20): 30-59% of expected = mild penalty band",
        module="optimizer/fa_recommender.py",
        sensitivity="MEDIUM",
        description="Lower bound of the mild PT penalty band (above this, ratio_full_credit applies)",
    ),
    "pt_hitter_gp_per_day": ConstantEntry(
        value=0.85,
        lower_bound=0.70,
        upper_bound=0.95,
        citation="FA P3.9 PR21 (2026-05-20): typical hitter starter plays ~0.85 GP/day (off days + rest)",
        module="optimizer/fa_recommender.py",
        sensitivity="LOW",
        description="Expected games-played per calendar day for a starting hitter",
    ),
    "pt_pitcher_ip_per_day": ConstantEntry(
        value=1.0,
        lower_bound=0.7,
        upper_bound=1.5,
        citation="FA P3.9 PR21 (2026-05-20): typical blended SP+RP yields ~1.0 IP/day at the team level",
        module="optimizer/fa_recommender.py",
        sensitivity="LOW",
        description="Expected IP per calendar day for a starting/rostered pitcher",
    ),
    "pt_mult_zero_volume": ConstantEntry(
        value=0.30,
        lower_bound=0.10,
        upper_bound=0.60,
        citation="FA P3.9 PR21 (2026-05-20): 0 GP / 0 IP exactly → heavy 0.30x penalty (likely IL stash phantom)",
        module="optimizer/fa_recommender.py",
        sensitivity="HIGH",
        description="Multiplier when player has 0 GP/IP YTD (after grace period)",
    ),
    "pt_mult_low": ConstantEntry(
        value=0.60,
        lower_bound=0.40,
        upper_bound=0.80,
        citation="FA P3.9 PR21 (2026-05-20): 1-29% of expected PT → 0.60x heavy penalty",
        module="optimizer/fa_recommender.py",
        sensitivity="MEDIUM",
        description="Multiplier for the low PT band (below ratio_mild)",
    ),
    "pt_mult_mild": ConstantEntry(
        value=0.85,
        lower_bound=0.70,
        upper_bound=0.95,
        citation="FA P3.9 PR21 (2026-05-20): 30-59% of expected PT → 0.85x mild penalty",
        module="optimizer/fa_recommender.py",
        sensitivity="MEDIUM",
        description="Multiplier for the mild PT band (ratio_mild ≤ x < ratio_full_credit)",
    ),
    "category_worsen_threshold": ConstantEntry(
        value=-0.1,
        lower_bound=-0.5,
        upper_bound=-0.01,
        citation="Internal heuristic 2026-05-20 (FA P3 baseline): swap is allowed to worsen a category by at most 0.1 SGP",
        module="optimizer/fa_recommender.py",
        sensitivity="MEDIUM",
        description="Per-category SGP loss threshold below which a swap is flagged as 'worsening' that category",
    ),
    "cross_type_sgp_min": ConstantEntry(
        value=0.3,
        lower_bound=0.1,
        upper_bound=1.0,
        citation="Internal heuristic 2026-05-20 (FA P3 baseline): cross-type (hitter→pitcher / vice versa) swaps must clear 0.3 SGP gain to overcome positional friction",
        module="optimizer/fa_recommender.py",
        sensitivity="MEDIUM",
        description="Minimum net SGP for a cross-type FA swap to be surfaced",
    ),
    "stream_net_sgp_min": ConstantEntry(
        value=0.70,
        lower_bound=0.20,
        upper_bound=1.50,
        citation="Internal heuristic 2026-05-20 (FA P3 baseline): minimum net SGP gain to surface a streamer; relaxed to stream_net_sgp_relaxed when below IP target",
        module="optimizer/fa_recommender.py",
        sensitivity="HIGH",
        description="Default minimum net SGP for a streaming pickup",
    ),
    "stream_net_sgp_relaxed": ConstantEntry(
        value=0.40,
        lower_bound=0.10,
        upper_bound=1.00,
        citation="Internal heuristic 2026-05-20 (FA P3 baseline): relaxed streaming SGP bar when projected weekly IP < 75% of stream_ip_target",
        module="optimizer/fa_recommender.py",
        sensitivity="HIGH",
        description="Relaxed minimum net SGP for pitcher streams when below IP target",
    ),
    "stream_hurt_threshold": ConstantEntry(
        value=-0.10,
        lower_bound=-0.50,
        upper_bound=-0.01,
        citation="Internal heuristic 2026-05-20 (FA P3 baseline): max allowed hurt on protected categories before a stream is suppressed",
        module="optimizer/fa_recommender.py",
        sensitivity="MEDIUM",
        description="Per-category SGP hurt below which a streamer is suppressed on protected categories",
    ),
    "stream_ip_target": ConstantEntry(
        value=54,
        lower_bound=42,
        upper_bound=66,
        citation="FourzynBurn weekly IP goal: 12 SP starts/team × ~6.5 IP/start. Mirrors default_team_weekly_ip; PR9 (2026-05-21)",
        module="optimizer/fa_recommender.py",
        sensitivity="MEDIUM",
        description="Weekly IP goal for the FA engine's streaming heuristics",
    ),
    "stream_ip_min": ConstantEntry(
        value=20,
        lower_bound=10,
        upper_bound=40,
        citation="Yahoo forfeit line: weekly IP floor below which the W/L/SV/K/ERA/WHIP categories forfeit",
        module="optimizer/fa_recommender.py",
        sensitivity="HIGH",
        description="Weekly IP minimum (Yahoo forfeit line)",
    ),
    "min_active_hitters": ConstantEntry(
        value=10,
        lower_bound=8,
        upper_bound=13,
        citation="FourzynBurn roster construction: 1C+1·1B+1·2B+1·3B+1SS+3OF+2Util = 10 starting hitters; FA P3.5 PR16",
        module="optimizer/fa_recommender.py",
        sensitivity="LOW",
        description="Starting-hitter minimum below which the FA engine refuses to surface a drop",
    ),
    "min_active_pitchers": ConstantEntry(
        value=8,
        lower_bound=6,
        upper_bound=10,
        citation="FourzynBurn roster construction: 2SP+2RP+4P = 8 starting pitchers; FA P3.5 PR16",
        module="optimizer/fa_recommender.py",
        sensitivity="LOW",
        description="Starting-pitcher minimum below which the FA engine refuses to surface a drop",
    ),
    # -- FA Recommender ECR + regression nudges (FA-E4 — 2026-06-07) -------
    # The last inline FA tunables: the ECR-rank-stddev consensus nudge and the
    # regression-flag (BUY_LOW/SELL_HIGH) nudge magnitudes. Centralized so
    # sensitivity_analysis / sigmoid_calibrator treat them as first-class
    # inputs. Values unchanged from the pre-FA-E4 inline literals.
    "ecr_stddev_polarizing_threshold": ConstantEntry(
        value=20,
        lower_bound=10,
        upper_bound=40,
        citation="FA P3 T3-4 heuristic (2026-05-20): ECR rank stddev above ~20 across sources = polarizing pick (analysts disagree), apply small discount",
        module="optimizer/fa_recommender.py",
        sensitivity="LOW",
        description="ECR rank stddev above which a FA is treated as a polarizing pick",
    ),
    "ecr_stddev_consensus_threshold": ConstantEntry(
        value=5,
        lower_bound=2,
        upper_bound=15,
        citation="FA P3 T3-4 heuristic (2026-05-20): ECR rank stddev below ~5 across sources = strong consensus pick, apply small premium",
        module="optimizer/fa_recommender.py",
        sensitivity="LOW",
        description="ECR rank stddev below which a FA is treated as a consensus pick",
    ),
    "ecr_polarizing_mult": ConstantEntry(
        value=0.95,
        lower_bound=0.85,
        upper_bound=0.99,
        citation="FA P3 T3-4 heuristic (2026-05-20): 5% composite discount for polarizing (high-stddev) ECR picks",
        module="optimizer/fa_recommender.py",
        sensitivity="LOW",
        description="Composite multiplier applied to polarizing-ECR FAs",
    ),
    "ecr_consensus_mult": ConstantEntry(
        value=1.02,
        lower_bound=1.01,
        upper_bound=1.10,
        citation="FA P3 T3-4 heuristic (2026-05-20): 2% composite premium for consensus (low-stddev) ECR picks",
        module="optimizer/fa_recommender.py",
        sensitivity="LOW",
        description="Composite multiplier applied to consensus-ECR FAs",
    ),
    "regression_buy_low_mult": ConstantEntry(
        value=1.05,
        lower_bound=1.01,
        upper_bound=1.15,
        citation="FA PR10 Part A (2026-05-20): xwOBA-wOBA / similar regression signals are ~5-10% accurate over one matchup, so a 5% BUY_LOW nudge is the right order of magnitude",
        module="optimizer/fa_recommender.py",
        sensitivity="MEDIUM",
        description="Composite multiplier applied to BUY_LOW regression-flagged FAs",
    ),
    "regression_sell_high_mult": ConstantEntry(
        value=0.95,
        lower_bound=0.85,
        upper_bound=0.99,
        citation="FA PR10 Part A (2026-05-20): symmetric counterpart of regression_buy_low_mult — 5% discount for SELL_HIGH regression-flagged FAs",
        module="optimizer/fa_recommender.py",
        sensitivity="MEDIUM",
        description="Composite multiplier applied to SELL_HIGH regression-flagged FAs",
    ),
    # -- Stream Analyzer (Pitcher Streaming page — 2026-06-10 design) -------
    # Component weights of the 0-100 Stream Score (convex blend, sum == 1.0).
    # Guarded by tests/test_stream_analyzer_constants_registered.py; read at
    # call time so sigmoid_calibrator/sensitivity_analysis can perturb them.
    "stream_score_w_matchup": ConstantEntry(
        value=0.35,
        lower_bound=0.20,
        upper_bound=0.50,
        citation="Pitcher Streaming Analyzer design 2026-06-09 §5: pitcher-quality-vs-opponent matchup score (two_start.compute_pitcher_matchup_score) is the primary streaming signal per Razzball/Pitcher List stream-o-nator practice",
        module="optimizer/stream_analyzer.py",
        sensitivity="HIGH",
        description="Stream Score weight: matchup score component",
    ),
    "stream_score_w_sgp": ConstantEntry(
        value=0.25,
        lower_bound=0.10,
        upper_bound=0.40,
        citation="Pitcher Streaming Analyzer design 2026-06-09 §5: marginal SGP via compute_streaming_value ties the score to actual category movement",
        module="optimizer/stream_analyzer.py",
        sensitivity="HIGH",
        description="Stream Score weight: marginal-SGP component",
    ),
    "stream_score_w_form": ConstantEntry(
        value=0.15,
        lower_bound=0.05,
        upper_bound=0.30,
        citation="Pitcher Streaming Analyzer design 2026-06-09 §5: L14-vs-season form delta, bounded by the existing ±20% form multiplier clip",
        module="optimizer/stream_analyzer.py",
        sensitivity="MEDIUM",
        description="Stream Score weight: recent-form component",
    ),
    "stream_score_w_lineup": ConstantEntry(
        value=0.10,
        lower_bound=0.00,
        upper_bound=0.25,
        citation="Pitcher Streaming Analyzer design 2026-06-09 §5: regressed PvB/lineup exposure (60-PA stabilization); neutral when lineups unposted",
        module="optimizer/stream_analyzer.py",
        sensitivity="MEDIUM",
        description="Stream Score weight: opposing-lineup / PvB exposure component",
    ),
    "stream_score_w_env": ConstantEntry(
        value=0.10,
        lower_bound=0.00,
        upper_bound=0.25,
        citation="Pitcher Streaming Analyzer design 2026-06-09 §5: park × weather environment multiplier (dome ⇒ park-only)",
        module="optimizer/stream_analyzer.py",
        sensitivity="MEDIUM",
        description="Stream Score weight: environment (park x weather) component",
    ),
    "stream_score_w_winprob": ConstantEntry(
        value=0.05,
        lower_bound=0.00,
        upper_bound=0.15,
        citation="Pitcher Streaming Analyzer design 2026-06-09 §5: team-strength win-probability proxy from compute_bayesian_stream_score (W category upside)",
        module="optimizer/stream_analyzer.py",
        sensitivity="LOW",
        description="Stream Score weight: win-probability component",
    ),
    # Risk-flag thresholds for the stream board.
    "stream_risk_short_leash_ip": ConstantEntry(
        value=4.5,
        lower_bound=3.5,
        upper_bound=5.5,
        citation="Pitcher Streaming Analyzer design 2026-06-09 §5: projected IP/start under ~4.5 signals a short leash / bullpen-day risk (league avg start ≈ 5.2 IP, 2024-2025)",
        module="optimizer/stream_analyzer.py",
        sensitivity="MEDIUM",
        description="SHORT_LEASH risk flag: projected IP per start below this",
    ),
    "stream_risk_elite_offense_wrc": ConstantEntry(
        value=110,
        lower_bound=105,
        upper_bound=120,
        citation="Pitcher Streaming Analyzer design 2026-06-09 §5: opponent wRC+ at or above ~110 is a top-5 offense in a typical season (FanGraphs team leaderboards)",
        module="optimizer/stream_analyzer.py",
        sensitivity="MEDIUM",
        description="ELITE_OFFENSE risk flag: opponent wRC+ at/above this",
    ),
    "stream_risk_hitter_park": ConstantEntry(
        value=1.08,
        lower_bound=1.03,
        upper_bound=1.15,
        citation="Pitcher Streaming Analyzer design 2026-06-09 §5: park factor >= ~1.08 marks the top hitter-friendly venues (COL/CIN tier, FanGraphs 5yr park factors)",
        module="optimizer/stream_analyzer.py",
        sensitivity="LOW",
        description="HITTER_PARK risk flag: venue park factor at/above this",
    ),
    "stream_loss_decision_share": ConstantEntry(
        value=0.65,
        lower_bound=0.40,
        upper_bound=0.90,
        citation="MLB starter decision rates: ~2/3 of starts end in a W or L for the starter (Baseball-Reference team pitching splits, 2022-2025); expected L per start = (1 - win_prob) x share",
        module="optimizer/stream_analyzer.py",
        sensitivity="MEDIUM",
        description="Share of non-win starts charged as a pitcher Loss in matchup-impact projection",
    ),
    "stream_risk_wind_out_mph": ConstantEntry(
        value=12.0,
        lower_bound=8.0,
        upper_bound=18.0,
        citation="Pitcher Streaming Analyzer design 2026-06-09 §5: outbound wind >= ~12 mph materially boosts HR rates in open parks (Alan Nathan wind-effect studies)",
        module="optimizer/stream_analyzer.py",
        sensitivity="LOW",
        description="WIND_OUT risk flag: outbound wind speed (mph) at/above this in open-air parks",
    ),
}
